chore: env -> vars 오타 수정 (#102)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -60,12 +60,12 @@ jobs:
 
       - name: Copy deployment script
         run: |
-          scp -P ${{ secrets.SSH_PORT }} deploy.sh nara@${{ secrets.SSH_HOST }}:${{ env.BASE_DIR }}
+          scp -P ${{ secrets.SSH_PORT }} deploy.sh nara@${{ secrets.SSH_HOST }}:${{ vars.BASE_DIR }}
 
       - name: Deploy to Server
         id: deploy
         run: |
-          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} nara@${{ secrets.SSH_HOST }} "bash ${{ env.BASE_DIR }}/deploy.sh ${{ env.DEPLOY_ENV }}" || echo "::set-output name=status::failed"
+          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} nara@${{ secrets.SSH_HOST }} "bash ${{ vars.BASE_DIR }}/deploy.sh ${{ env.DEPLOY_ENV }}" || echo "::set-output name=status::failed"
 
       - name: Check deployment status
         if: steps.deploy.outputs.status == 'failed'
