chore: 서버 포트 및 호스트 변수 처리 (#102)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -52,20 +52,20 @@ jobs:
 
           if [[ "$DEPLOY_ENV" == "production" ]]; then
             echo "Using production deployment target"
-            echo "APP_URL=http://110.15.18.54:4000" >> $GITHUB_ENV
+            echo "APP_URL=http://${{ secrets.SSH_HOST }}:4000" >> $GITHUB_ENV
           else
             echo "Using staging deployment target"
-            echo "APP_URL=http://110.15.18.54:3000" >> $GITHUB_ENV
+            echo "APP_URL=http://${{ secrets.SSH_HOST }}:3000" >> $GITHUB_ENV
           fi
 
       - name: Copy deployment script
         run: |
-          scp -P 10122 deploy.sh nara@110.15.18.54:/home/nara/speller-front
+          scp -P ${{ secrets.SSH_PORT }} deploy.sh nara@${{ secrets.SSH_HOST }}:${{ env.BASE_DIR }}
 
       - name: Deploy to Server
         id: deploy
         run: |
-          ssh -o StrictHostKeyChecking=no -p 10122 nara@110.15.18.54 "bash /home/nara/speller-front/deploy.sh ${{ env.DEPLOY_ENV }}" || echo "::set-output name=status::failed"
+          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} nara@${{ secrets.SSH_HOST }} "bash ${{ env.BASE_DIR }}/deploy.sh ${{ env.DEPLOY_ENV }}" || echo "::set-output name=status::failed"
 
       - name: Check deployment status
         if: steps.deploy.outputs.status == 'failed'
